spring.application.name: GalGameSite

server:
  port: 8080

spring:
  main:
    allow-circular-references: true   # ??????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/game_and_love?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: j

mybatis-plus:
  type-aliases-package: yumefusaka.galgamesite.pojo.Entity # ?????
  mapper-locations: "classpath*:/mapper/**/*.xml" # Mapper.xml????????
  configuration:
    map-underscore-to-camel-case: false # ?????????????
    cache-enabled: false # ????????
  global-config:
    db-config:
      update-strategy: not_null # ????????????

logging:
  level:
    yumefusaka:
      galgamesite:
        mapper: debug
        service: info
        controller: info

# jwt????
jwt:
  token-name: token
  ttl: 432000000000
  secret-key: yumefusaka


# knife4j????
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

